# permissions for end users to view upgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upgrade-viewer-role
rules:
- apiGroups:
  - octeondpu.marvell.com
  resources:
  - upgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - octeondpu.marvell.com
  resources:
  - upgrades/status
  verbs:
  - get
